# ===========================================
# DIGITAL TWIN PLATFORM - SECURITY CONFIG
# ===========================================

# Configurazione generale di sicurezza
security:
  enabled: true # Abilita controlli di sicurezza globali
  enforce_tenant_isolation: true # Isolamento rigoroso per tenant
  require_ownership_for_write: true # Ownership necessario per operazioni di scrittura
  require_ownership_for_execute: true # Ownership necessario per esecuzione capabilities
  default_secure_twins: true # Nuovi Digital Twin sicuri per default
  log_all_access: true # Log di tutti gli accessi ai twin

  # Controlli di accesso avanzati
  access_control:
    cache_permissions: true # Cache delle autorizzazioni in Redis
    permission_cache_ttl: 300 # TTL cache permessi (secondi)
    max_authorized_users_per_twin: 50 # Limite utenti autorizzati per twin
    auto_revoke_inactive_users: true # Revoca automatica utenti inattivi
    inactive_threshold_days: 90 # Soglia inattività (giorni)

# Configurazione autenticazione
auth:
  require_email_verification: false # Verifica email obbligatoria
  jwt:
    secret_key: "your-super-secret-jwt-key-change-in-production"
    access_token_expire_minutes: 60 # Scadenza access token
    refresh_token_expire_days: 7 # Scadenza refresh token

  # Rate limiting
  rate_limiting:
    enabled: true
    max_auth_attempts: 10 # Tentativi di auth per IP
    lockout_duration: 300 # Durata lockout (secondi)

  # Password policy
  password_policy:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: false

# Configurazione storage sicuro
storage:
  primary_type: "mongodb" # mongodb | memory
  cache_type: "redis" # redis | none
  separate_dbs_per_twin: true # Database separati per ogni tenant
  encrypt_sensitive_data: true # Crittografia dati sensibili

  # MongoDB settings
  mongodb:
    connection_string: "mongodb://localhost:27017"
    database_prefix: "dt_platform" # Prefisso database
    max_pool_size: 50
    timeout_ms: 5000

  # Redis settings
  redis:
    host: "localhost"
    port: 6379
    database: 0
    max_connections: 20
    password: null # Password Redis (se configurata)

# Configurazione API sicura
api:
  host: "0.0.0.0"
  port: 8000

  # CORS settings
  cors_origins:
    - "http://localhost:3000" # Frontend dev
    - "http://localhost:8080" # Frontend prod
    - "https://yourdomain.com" # Production domain

  allowed_hosts: ["*"] # Host consentiti (["*"] per tutti)

  # Security headers
  security_headers:
    enable_hsts: true # HTTP Strict Transport Security
    enable_csrf_protection: true # CSRF protection
    content_security_policy: "default-src 'self'"

  # Request limits
  request_limits:
    max_request_size: "10MB" # Dimensione massima richiesta
    rate_limit_per_minute: 100 # Richieste per minuto per IP

# Configurazione Digital Twin Identity
digital_twin_identity:
  enabled: true # Abilita certificati per DT
  certificate_validity_days: 365 # Validità certificati
  auto_rotate_credentials: true # Rotazione automatica credenziali
  rotation_threshold_days: 30 # Soglia per rotazione

# Configurazione tenant
tenant:
  multi_tenant_enabled: true # Supporto multi-tenant
  default_plan: "free" # Piano default per nuovi tenant

  # Limiti per piano
  plan_limits:
    free:
      max_digital_twins: 5
      max_users: 3
      storage_gb: 1
      api_requests_per_day: 1000
    pro:
      max_digital_twins: 50
      max_users: 25
      storage_gb: 100
      api_requests_per_day: 50000
    enterprise:
      max_digital_twins: -1 # Illimitato
      max_users: -1 # Illimitato
      storage_gb: -1 # Illimitato
      api_requests_per_day: -1 # Illimitato

# Configurazione logging di sicurezza
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  security_events:
    log_authentication: true # Log eventi autenticazione
    log_authorization: true # Log controlli autorizzazione
    log_twin_access: true # Log accessi ai twin
    log_capability_execution: true # Log esecuzioni capabilities
    log_access_changes: true # Log modifiche permessi

  # Audit trail
  audit:
    enabled: true # Abilita audit trail completo
    retention_days: 365 # Retention log audit
    include_sensitive_data: false # Include dati sensibili nei log

# Configurazione di development/testing
development:
  create_default_users: true # Crea utenti di default
  enable_debug_endpoints: true # Abilita endpoint di debug
  mock_external_services: false # Mock servizi esterni
  skip_email_verification: true # Salta verifica email in dev

# Configurazione feature flags
features:
  enhanced_analytics: true # Analytics avanzate
  workflow_engine: true # Engine workflow
  real_time_monitoring: true # Monitoring real-time
  ai_recommendations: false # Raccomandazioni AI (experimental)
  blockchain_integration: false # Integrazione blockchain (experimental)

# Configurazione backup e recovery
backup:
  enabled: false # Backup automatico
  schedule: "0 2 * * *" # Cron schedule (2 AM daily)
  retention_days: 30 # Retention backup
  include_sensitive_data: false # Include dati sensibili nel backup

# Configurazione monitoring
monitoring:
  enabled: true # Monitoring applicazione
  metrics_endpoint: "/metrics" # Endpoint metriche Prometheus
  health_check_interval: 30 # Intervallo health check (secondi)

  # Alerting
  alerts:
    enabled: true
    security_threshold: 10 # Soglia eventi sicurezza per alert
    performance_threshold: 1000 # Soglia performance (ms) per alert
